[tool.flit.metadata]
module = "zsh_kernel"
author = "Daniel Bayley"
author-email = "daniel.bayley@me.com"
home-page = "https://github.com/danielbayley/zsh_kernel"
requires = ["pexpect (>=4.0)"]
description-file = "README.md"
classifiers = Framework :: Jupyter
  License :: OSI Approved :: MIT License
  Programming Language :: Python :: 3
  Topic :: System :: Shells
